---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:year ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: rouge

### content configuration ###
title:       "Take the Credit"
keywords:    "Baltimore, property tax, tax credit"
description: "A site to help Baltimore residents get property tax credits"
source_link: "https://ryan-j-smith.github.io/baltimore-credit-site"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-67607917-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false

